#!/bin/env bash
# audit-report.sh - Generate comprehensive audit reports

generate_audit_report() {
    local user=$(whoami)
    local report_date=$(date +%Y%m%d_%H%M%S)
    local report_file="/tmp/fintech-audit-$report_date.txt"
    
    # Only auditors can generate full reports
    if ! id -nG "$user" | grep -q "fintech-auditors"; then
        echo "Warning: Limited audit view. Full audit requires auditor privileges."
    fi
    
    {
        echo "=========================================="
        echo "   SECUREPAY FINTECH - AUDIT REPORT"
        echo "=========================================="
        echo "Report ID: AUD-$(date +%Y%m%d-%H%M%S)"
        echo "Generated by: $user"
        echo "Timestamp: $(date)"
        echo "Environment: $(hostname)"
        echo ""
        
        echo "SECTION 1: TRANSACTION SUMMARY"
        echo "------------------------------"
        local total_tx=$(wc -l < "$DATA_DIR/transactions.csv")
        local total_tx=$((total_tx - 1))  # Subtract header
        local flagged_tx=$(grep -c "TRUE" "$DATA_DIR/transactions.csv")
        local total_volume=$(awk -F',' 'NR>1 {sum+=$6} END {printf "%.2f", sum}' "$DATA_DIR/transactions.csv")
        
        echo "Total Transactions: $total_tx"
        echo "Flagged Transactions: $flagged_tx"
        echo "Total Volume: $total_volume USD"
        echo ""
        
        echo "SECTION 2: USER ACCESS AUDIT"
        echo "----------------------------"
        echo "Active Sessions:"
        who | while read session; do
            echo "  - $session"
        done
        echo ""
        
        echo "Recent Logins (last 10):"
        last -10 | head -10
        echo ""
        
        echo "SECTION 3: SYSTEM SECURITY STATUS"
        echo "---------------------------------"
        echo "Firewall Status: $(sudo ufw status 2>/dev/null || echo "Not configured")"
        echo "Failed Logins: $(grep -c "Failed password" /var/log/auth.log 2>/dev/null || echo "N/A")"
        echo "Open Ports:"
        netstat -tulpn 2>/dev/null | grep LISTEN | head -10
        echo ""
        
        echo "SECTION 4: COMPLIANCE CHECKLIST"
        echo "-------------------------------"
        
        # Check PCI-DSS requirements
        echo "PCI-DSS Compliance:"
        echo "  ✓ Encryption at rest: $(test -f /opt/fintech-security/encryption/keys && echo "YES" || echo "NO")"
        echo "  ✓ Audit logging: $(test -f "$LOG_FILE" && echo "YES" || echo "NO")"
        echo "  ✓ Access control: $(ls -la /opt/fintech-security/ | grep -c "drwx" | awk '{print "YES (" $0 " directories)"}')"
        
        echo ""
        echo "SECTION 5: SUSPICIOUS ACTIVITIES"
        echo "--------------------------------"
        if [ -f "$DATA_DIR/suspicious-activity.log" ]; then
            tail -20 "$DATA_DIR/suspicious-activity.log" | while read line; do
                echo "  ⚠️  $line"
            done
        else
            echo "  No suspicious activities logged"
        fi
        
        echo ""
        echo "=========================================="
        echo "END OF AUDIT REPORT"
        echo "=========================================="
        
    } > "$report_file"
    
    # Set proper permissions on report
    chmod 640 "$report_file"
    
    echo "Audit report generated: $report_file"
    
    # If auditor, encrypt the report
    if id -nG "$user" | grep -q "fintech-auditors"; then
        gpg --encrypt --recipient audit@securepay.com "$report_file" 2>/dev/null && \
            echo "Report encrypted for audit trail"
    fi
    
    log_audit "INFO" "$user" "Generated audit report: $report_file" "SUCCESS"
}
